ARG PYTHON_VERSION

FROM python:${PYTHON_VERSION}

WORKDIR /app

COPY requirements/ /app/requirements/
RUN pip install -r requirements/local.txt

COPY MANIFEST.in setup.py tox.ini /app/
COPY src/ /app/src/

ENTRYPOINT ["/usr/local/bin/tox", "-e"]
